### ISSUE TITLE
你好，有问题请问大佬

### ISSUE THREAD

**Issue by shiboys** [inacos/spring-cloud-nacos#2]
“2.在线动态扩容Eureka Server，替换其中的1-2两台Eureka Server。”
这个替换其中1-2台Eureka Server 为什么要替换，被替换的Eureka Server  然后做什么用。你的这个应用是直接部署在被替换下来的Eureka Server  吗？

**Comment by charlesvhe** [comment]
假设你之前已经部署了2台eureka做高可用，由于eureka之间是有自动同步的，你只需再部署一台eureka-proxy即可，对原有部署架构无侵入。新部署的eureka-proxy会同步现有注册信息，然后注册到nacos里，eureka-proxy从nacos里获取的注册信息也会使用eureka自动同步机制，同步到原有的2台eureka里。
